# This pipeline uses the https://woodpecker-ci.org/plugins/Docker%20Buildx plugin

variables:
  - &repo 'docker.io/devture/matrix-corporal'
  - &dockerfile 'etc/docker/Dockerfile'
  - &platforms 'linux/amd64,linux/arm64/v8,linux/arm/v7'

steps:
  build-and-push-for-branch:
    when:
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}
      - event: manual
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: *repo
      tag: latest
      dockerfile: *dockerfile
      platforms: *platforms

  build-and-push-for-tag:
    when:
      - event: tag
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: *repo
      tag: ${CI_COMMIT_TAG}
      dockerfile: *dockerfile
      platforms: *platforms
