# This pipeline uses the https://woodpecker-ci.org/plugins/Docker%20Buildx plugin

variables:
  - &repo 'docker.io/devture/matrix-corporal'
  - &dockerfile 'etc/docker/Dockerfile'
  - &platforms 'linux/amd64,linux/arm64/v8,linux/arm/v7'
  - &builder_image woodpeckerci/plugin-docker-buildx:5.2.0

services:
  docker:
    image: docker:27.5.1-dind
    commands:
      - dockerd --tls=false --host=tcp://0.0.0.0:2376
    privileged: true

steps:
  - name: build-and-push-for-branch
    when:
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}
      - event: manual
    image: *builder_image
    settings:
      repo: *repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag: latest
      dockerfile: *dockerfile
      platforms: *platforms

  - name: build-and-push-for-tag
    when:
      - event: tag
    image: *builder_image
    settings:
      repo: *repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag: ${CI_COMMIT_TAG}
      dockerfile: *dockerfile
      platforms: *platforms
